#!/usr/bin/bash

APP_ROOT=/usr/local/fw
SYSTEMD_ROOT=/usr/lib/systemd/system

function systemd_uninstall() {
	app=$1
	app_unit=$APP_ROOT/systemd/$app.service

	if systemctl is-active $app.service; then
		systemctl stop $app.service
	fi

	if systemctl is-active $app.service; then
		systemctl disable $app.service
	fi

    if -d $APP_ROOT; then 
	    echo "fw systemd service units are removed."
	    rm -f $SYSTEMD_ROOT/$app.service
	    systemctl daemon-reload
        rm -rf $APP_ROOT
    fi
}

systemd_uninstall fw
