// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: fw.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BpfFwRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol    uint32 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SrcIp       uint32 `protobuf:"varint,2,opt,name=srcIp,proto3" json:"srcIp,omitempty"`
	SrcIpMask   uint32 `protobuf:"varint,3,opt,name=srcIpMask,proto3" json:"srcIpMask,omitempty"`
	SrcPort     uint32 `protobuf:"varint,4,opt,name=srcPort,proto3" json:"srcPort,omitempty"`
	SrcPortMask uint32 `protobuf:"varint,5,opt,name=srcPortMask,proto3" json:"srcPortMask,omitempty"`
	DstIp       uint32 `protobuf:"varint,6,opt,name=dstIp,proto3" json:"dstIp,omitempty"`
	DstIpMask   uint32 `protobuf:"varint,7,opt,name=dstIpMask,proto3" json:"dstIpMask,omitempty"`
	DstPort     uint32 `protobuf:"varint,8,opt,name=dstPort,proto3" json:"dstPort,omitempty"`
	DstPortMask uint32 `protobuf:"varint,9,opt,name=dstPortMask,proto3" json:"dstPortMask,omitempty"`
	Action      uint32 `protobuf:"varint,10,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *BpfFwRule) Reset() {
	*x = BpfFwRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BpfFwRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BpfFwRule) ProtoMessage() {}

func (x *BpfFwRule) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BpfFwRule.ProtoReflect.Descriptor instead.
func (*BpfFwRule) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{0}
}

func (x *BpfFwRule) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *BpfFwRule) GetSrcIp() uint32 {
	if x != nil {
		return x.SrcIp
	}
	return 0
}

func (x *BpfFwRule) GetSrcIpMask() uint32 {
	if x != nil {
		return x.SrcIpMask
	}
	return 0
}

func (x *BpfFwRule) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *BpfFwRule) GetSrcPortMask() uint32 {
	if x != nil {
		return x.SrcPortMask
	}
	return 0
}

func (x *BpfFwRule) GetDstIp() uint32 {
	if x != nil {
		return x.DstIp
	}
	return 0
}

func (x *BpfFwRule) GetDstIpMask() uint32 {
	if x != nil {
		return x.DstIpMask
	}
	return 0
}

func (x *BpfFwRule) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *BpfFwRule) GetDstPortMask() uint32 {
	if x != nil {
		return x.DstPortMask
	}
	return 0
}

func (x *BpfFwRule) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type FwRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//eg: TCP UDP ICMP GRE
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	//eg:
	//11.11.11.11
	//11.11.11.11/24
	//0.0.0.0/0
	//0.0.0.0/32
	SrcIp string `protobuf:"bytes,2,opt,name=srcIp,proto3" json:"srcIp,omitempty"`
	DstIp string `protobuf:"bytes,3,opt,name=dstIp,proto3" json:"dstIp,omitempty"`
	//eg:
	//1-65535
	//22
	//3389
	//11-1111
	SrcPort string `protobuf:"bytes,4,opt,name=srcPort,proto3" json:"srcPort,omitempty"`
	DstPort string `protobuf:"bytes,5,opt,name=dstPort,proto3" json:"dstPort,omitempty"`
	//eg:
	//accept
	//drop
	Action string `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *FwRule) Reset() {
	*x = FwRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FwRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FwRule) ProtoMessage() {}

func (x *FwRule) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FwRule.ProtoReflect.Descriptor instead.
func (*FwRule) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{1}
}

func (x *FwRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FwRule) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *FwRule) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *FwRule) GetSrcPort() string {
	if x != nil {
		return x.SrcPort
	}
	return ""
}

func (x *FwRule) GetDstPort() string {
	if x != nil {
		return x.DstPort
	}
	return ""
}

func (x *FwRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` //错误码
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    //错误简要
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action  string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`   //请求操作
	TraceId string `protobuf:"bytes,2,opt,name=traceId,proto3" json:"traceId,omitempty"` //请求TraceId
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{3}
}

func (x *ActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors  []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`   //错误集
	Code    uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      //HTTP状态码
	TraceId string   `protobuf:"bytes,3,opt,name=traceId,proto3" json:"traceId,omitempty"` //信息简要
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fw_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{4}
}

func (x *ActionResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ActionResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ActionResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_fw_proto protoreflect.FileDescriptor

var file_fw_proto_rawDesc = []byte{
	0x0a, 0x08, 0x66, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x66, 0x77, 0x22, 0x9f,
	0x02, 0x0a, 0x09, 0x62, 0x70, 0x66, 0x46, 0x77, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x72, 0x63, 0x49,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x72, 0x63, 0x49, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x72, 0x63, 0x49, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x73, 0x72, 0x63, 0x49, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73,
	0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x72, 0x63, 0x50, 0x6f, 0x72,
	0x74, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x72, 0x63,
	0x50, 0x6f, 0x72, 0x74, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x73, 0x74, 0x49,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x64, 0x73, 0x74, 0x49, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x73, 0x74, 0x49, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x64, 0x73, 0x74, 0x49, 0x70, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64,
	0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x73, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x4d, 0x61, 0x73, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x64, 0x73, 0x74,
	0x50, 0x6f, 0x72, 0x74, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x9c, 0x01, 0x0a, 0x06, 0x46, 0x77, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x72, 0x63, 0x49, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x72, 0x63, 0x49, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x73, 0x74, 0x49, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x73,
	0x74, 0x49, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x2d, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x41,
	0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49,
	0x64, 0x22, 0x61, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x66, 0x77, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x49, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fw_proto_rawDescOnce sync.Once
	file_fw_proto_rawDescData = file_fw_proto_rawDesc
)

func file_fw_proto_rawDescGZIP() []byte {
	file_fw_proto_rawDescOnce.Do(func() {
		file_fw_proto_rawDescData = protoimpl.X.CompressGZIP(file_fw_proto_rawDescData)
	})
	return file_fw_proto_rawDescData
}

var file_fw_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fw_proto_goTypes = []interface{}{
	(*BpfFwRule)(nil),      // 0: fw.bpfFwRule
	(*FwRule)(nil),         // 1: fw.FwRule
	(*Error)(nil),          // 2: fw.Error
	(*ActionRequest)(nil),  // 3: fw.ActionRequest
	(*ActionResponse)(nil), // 4: fw.ActionResponse
}
var file_fw_proto_depIdxs = []int32{
	2, // 0: fw.ActionResponse.errors:type_name -> fw.Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fw_proto_init() }
func file_fw_proto_init() {
	if File_fw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BpfFwRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FwRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fw_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fw_proto_goTypes,
		DependencyIndexes: file_fw_proto_depIdxs,
		MessageInfos:      file_fw_proto_msgTypes,
	}.Build()
	File_fw_proto = out.File
	file_fw_proto_rawDesc = nil
	file_fw_proto_goTypes = nil
	file_fw_proto_depIdxs = nil
}
